---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ami-sa
  namespace: kuberhealthy
---
apiVersion: kuberhealthy.github.io/v2
kind: HealthCheck
metadata:
  name: ami
  namespace: kuberhealthy
spec:
  runInterval: 30m
  timeout: 10m
  extraAnnotations:
    iam.amazonaws.com/role: <role-arn>
  podSpec:
    spec:
      containers:
        - name: ami
          image: kuberhealthy/ami-check:sha-<short-sha>
          imagePullPolicy: IfNotPresent
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_S3_BUCKET_NAME
              value: "s3-bucket-name"
            - name: CLUSTER_FQDN
              value: "cluster.k8s"
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 15m
      restartPolicy: Never
      serviceAccountName: ami-sa
